#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@palimpsest/scripts"
import pkg from "../package.json"

const modelsUrl = process.env.PALIMPSEST_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.ts"),
  `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)
console.log("Generated models-snapshot.ts")

async function loadMigrations(...roots: string[]) {
  const out = []
  for (const root of roots) {
    let entries: fs.Dirent[] = []
    try {
      entries = await fs.promises.readdir(root, { withFileTypes: true })
    } catch {
      continue
    }
    for (const entry of entries) {
      if (!entry.isDirectory() || !/^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name)) continue
      const file = path.join(root, entry.name, "migration.sql")
      const sql = await Bun.file(file).text()
      const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(entry.name)
      const timestamp = match
        ? Date.UTC(
            Number(match[1]),
            Number(match[2]) - 1,
            Number(match[3]),
            Number(match[4]),
            Number(match[5]),
            Number(match[6]),
          )
        : 0
      out.push({ sql, timestamp, name: entry.name })
    }
  }
  return out.sort((a, b) => a.timestamp - b.timestamp)
}

const migrations = await loadMigrations(path.join(dir, "migration"), path.resolve(dir, "../../packages/domain/migration"))
console.log(`Loaded ${migrations.length} migrations`)

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  { os: "linux", arch: "arm64" },
  { os: "linux", arch: "x64" },
  { os: "linux", arch: "x64", avx2: false },
  { os: "linux", arch: "arm64", abi: "musl" },
  { os: "linux", arch: "x64", abi: "musl" },
  { os: "linux", arch: "x64", abi: "musl", avx2: false },
]

const targets = singleFlag
  ? allTargets.filter((item) => {
      if (item.os !== process.platform || item.arch !== process.arch) {
        return false
      }

      // When building for the current platform, prefer a single native binary by default.
      // Baseline binaries require additional Bun artifacts and can be flaky to download.
      if (item.avx2 === false) {
        return baselineFlag
      }

      // also skip abi-specific builds for the same reason
      if (item.abi !== undefined) {
        return false
      }

      return true
    })
  : allTargets

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [
      {
        name: "force-node-pdf-parse",
        setup(build) {
          const pdfParseReal = fs.realpathSync(path.dirname(require.resolve("pdf-parse/package.json")))
          const pdfjsReal = fs.realpathSync(path.resolve(pdfParseReal, "../pdfjs-dist"))
          const pdfjsLegacy = path.resolve(pdfjsReal, "legacy/build")

          build.onResolve({ filter: /^pdf-parse$/ }, () => {
            return { path: path.resolve(pdfParseReal, "dist/pdf-parse/esm/index.js") }
          })

          build.onLoad({ filter: /pdfjs-dist.*legacy.*pdf\.mjs$/ }, async (args) => {
            let contents = await Bun.file(args.path).text()
            const workerPath = path.resolve(pdfjsLegacy, "pdf.worker.mjs")
            contents = contents.replace(
              `const worker = await import(\n      /*webpackIgnore: true*/\n      /*@vite-ignore*/\n      this.workerSrc)`,
              `const worker = await import(${JSON.stringify(workerPath)})`,
            )
            return { contents, loader: "js" }
          })
        },
      },
    ],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/palimpsest`,
      execArgv: [`--user-agent=palimpsest/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./src/index.ts"],
    define: {
      PALIMPSEST_VERSION: `'${Script.version}'`,
      PALIMPSEST_MIGRATIONS: JSON.stringify(migrations),
      PALIMPSEST_CHANNEL: `'${Script.channel}'`,
      PALIMPSEST_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
  }
  await $`gh release upload v${Script.version} ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
